remote_theme: pages-themes/midnight@v0.2.0
include:
  - style.css
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag

baseurl: "/poweroutageanalysis"
title: [Illuminating the Dark -- An In-Depth Analysis of Power Outage Data]
description: [By Atherv Vidhate and Zubin Sannakkayala]
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable_sanitization: true
